// <auto-generated />
using System;
using CCTaskScoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCTaskScoring.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("CCTaskScoring.Core.Models.RewardPunishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("rewards_punishments", (string)null);
                });

            modelBuilder.Entity("CCTaskScoring.Core.Models.ScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AutoScored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_scored");

                    b.Property<double>("CompletionScore")
                        .HasColumnType("REAL")
                        .HasColumnName("completion_score");

                    b.Property<double>("CorrectnessScore")
                        .HasColumnType("REAL")
                        .HasColumnName("correctness_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("EfficiencyScore")
                        .HasColumnType("REAL")
                        .HasColumnName("efficiency_score");

                    b.Property<double>("QualityScore")
                        .HasColumnType("REAL")
                        .HasColumnName("quality_score");

                    b.Property<string>("ReviewerComments")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_comments");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL")
                        .HasColumnName("total_score");

                    b.Property<double>("UxScore")
                        .HasColumnType("REAL")
                        .HasColumnName("ux_score");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("CCTaskScoring.Core.Models.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Artifacts")
                        .HasColumnType("TEXT")
                        .HasColumnName("artifacts");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Framework")
                        .HasColumnType("TEXT")
                        .HasColumnName("framework");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Logs")
                        .HasColumnType("TEXT")
                        .HasColumnName("logs");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("StaticAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("static_analysis");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TestResults")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_results");

                    b.HasKey("Id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("CCTaskScoring.Core.Models.RewardPunishment", b =>
                {
                    b.HasOne("CCTaskScoring.Core.Models.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CCTaskScoring.Core.Models.ScoreEntity", b =>
                {
                    b.HasOne("CCTaskScoring.Core.Models.TaskEntity", "Task")
                        .WithOne("Score")
                        .HasForeignKey("CCTaskScoring.Core.Models.ScoreEntity", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CCTaskScoring.Core.Models.TaskEntity", b =>
                {
                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
